import type { NetworkRecord } from '@/types/network';
import type { StatusInsight } from '@/types/insights';

/**
 * Generates local, rule-based diagnostic insights for HTTP requests.
 * Completely local-first with zero AI / LLM dependencies.
 */
export function getStatusInsight(record: NetworkRecord): StatusInsight | null {
  const status = record.status;
  const resHeaders = record.responseHeaders;
  const reqHeaders = record.requestHeaders;

  // Status 0: Network error / CORS blocked
  if (status === 0 || status === undefined) {
    return {
      code: status ?? 0,
      title: 'Request Blocked or Failed (Status 0)',
      message: 'The request failed before reaching the server, or the response was blocked by the browser.',
      severity: 'error',
      recommendations: [
        'CORS Preflight Failure: Verify server sends Access-Control-Allow-Origin headers.',
        'Network Disconnect: Verify your internet connection or server host address.',
        'Certificate Error: Check if the API uses an untrusted or self-signed SSL certificate.',
      ],
    };
  }

  // 2xx Success - No diagnostic errors needed
  if (status >= 200 && status < 300) {
    return null;
  }

  // 3xx Redirection
  if (status >= 300 && status < 400) {
    const location = resHeaders['location'];
    return {
      code: status,
      title: `${status} Redirection`,
      message: location ? `Request redirected to: ${location}` : 'Resource has moved or requires redirection.',
      severity: 'info',
      recommendations: [
        'Check if following redirects is expected for your client.',
        location ? `Update your client endpoint to ${location}` : 'Inspect the Location response header.',
      ],
    };
  }

  // 400 Bad Request
  if (status === 400) {
    return {
      code: 400,
      title: '400 Bad Request',
      message: 'The server could not understand the request due to invalid syntax or malformed payload.',
      severity: 'error',
      recommendations: [
        'Verify request payload format (JSON syntax, required fields).',
        'Check Content-Type header (e.g. application/json).',
        'Inspect server response body for validation error details.',
      ],
    };
  }

  // 401 Unauthorized
  if (status === 401) {
    const hasAuthHeader = !!reqHeaders['authorization'] || !!reqHeaders['x-api-key'] || !!reqHeaders['api-key'];
    if (!hasAuthHeader) {
      return {
        code: 401,
        title: '401 Unauthorized — Missing Authentication Header',
        message: 'This request did not include any Authorization or API-Key header.',
        severity: 'error',
        recommendations: [
          'Add an Authorization header (e.g. Authorization: Bearer <token>).',
          'Check if your auth token or login session has expired.',
          'Verify if the endpoint requires an API key in query params or headers.',
        ],
      };
    }

    return {
      code: 401,
      title: '401 Unauthorized — Authentication Failed',
      message: 'Authorization header was sent, but the credentials were rejected or expired.',
      severity: 'error',
      recommendations: [
        'Token Expiry: Check if your JWT or session token has expired.',
        'Token Signature: Verify the token was generated by the correct authority.',
        'Refresh Token: Trigger a token refresh before retrying this request.',
      ],
    };
  }

  // 403 Forbidden
  if (status === 403) {
    return {
      code: 403,
      title: '403 Forbidden',
      message: 'Authenticated successfully, but insufficient permissions to access this resource.',
      severity: 'error',
      recommendations: [
        'Check user roles and scopes required for this API route.',
        'Verify if your account or API key has write/read privileges.',
        'Inspect server response for specific permission requirement codes.',
      ],
    };
  }

  // 404 Not Found
  if (status === 404) {
    return {
      code: 404,
      title: '404 Not Found',
      message: 'The requested resource URL was not found on the server.',
      severity: 'warning',
      recommendations: [
        `Check route URL: "${record.path}". Ensure there are no typos.`,
        'Verify route parameters (IDs, slugs) exist on the server.',
        'Check if API base URL has a missing prefix (e.g. /api/v1).',
      ],
    };
  }

  // 409 Conflict
  if (status === 409) {
    return {
      code: 409,
      title: '409 Conflict',
      message: 'The request could not be completed due to a conflict with current resource state.',
      severity: 'warning',
      recommendations: [
        'Check for duplicate unique identifiers (e.g. email, username, slug already exists).',
        'Verify version or ETag concurrency conflicts.',
      ],
    };
  }

  // 422 Unprocessable Entity
  if (status === 422) {
    return {
      code: 422,
      title: '422 Unprocessable Entity',
      message: 'Request syntax is valid, but payload data failed server-side validation rules.',
      severity: 'warning',
      recommendations: [
        'Inspect response body for detailed field validation errors.',
        'Check data types, string length, regex constraints, or enum values.',
      ],
    };
  }

  // 429 Too Many Requests
  if (status === 429) {
    const retryAfter = resHeaders['retry-after'];
    const retryNote = retryAfter
      ? `Rate limit active. Server requests waiting ${retryAfter} seconds before retry.`
      : 'You have exceeded the rate limit for this endpoint.';

    return {
      code: 429,
      title: '429 Too Many Requests',
      message: retryNote,
      severity: 'warning',
      recommendations: [
        retryAfter ? `Wait ${retryAfter}s before sending next request.` : 'Implement exponential backoff in client code.',
        'Check X-RateLimit-Remaining / X-RateLimit-Reset headers.',
      ],
    };
  }

  // 500+ Server Errors
  if (status >= 500) {
    const isHtml = (record.mimeType || resHeaders['content-type'] || '').includes('html');
    const is502 = status === 502;
    const is503 = status === 503;
    const is504 = status === 504;

    let title = `${status} Internal Server Error`;
    let detail = 'An unhandled exception occurred on the remote server.';

    if (is502) {
      title = '502 Bad Gateway';
      detail = 'The gateway or reverse proxy received an invalid response from upstream.';
    } else if (is503) {
      title = '503 Service Unavailable';
      detail = 'The server is temporarily overloaded or undergoing maintenance.';
    } else if (is504) {
      title = '504 Gateway Timeout';
      detail = 'The upstream server took too long to respond before timeout.';
    }

    const recommendations = [
      'Inspect backend server logs for stack traces.',
      'The client request itself may be completely valid.',
    ];

    if (isHtml) {
      recommendations.unshift('Response is HTML: Likely a default proxy (Nginx/Cloudflare) or web framework error page.');
    }

    return {
      code: status,
      title,
      message: detail,
      severity: 'error',
      recommendations,
    };
  }

  return null;
}
